# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Programação para Ciência de Dados</span>

## <span style="color:blue">Numpy Parte I - Exercícios</span>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**

#### <span style="color:red">Recomenda-se fortemente que os exercícios sejam feitos sem consultar as respostas antecipadamente.</span>

In [1]:
import numpy as np

### Exercício 1)
Utilize comprehension para gerar a lista de todos os números inteiros entre 0 e 19. Converta a lista em um <font color='blue'>numpy</font> array bidimensional (matriz) com 4 linhas e 5 colunas.

In [10]:
lst = [i for i in range(20)]       # usando comprehension
lst = np.array(lst2).reshape(4,5)  # convertendo em np.array e redimensionando a matriz
lst

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
# usando numpy
lst2 = np.arange(20).reshape(4,5)
lst2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Exercício 2)
Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz `A` com 5 linhas e 6 colunas.

In [51]:
A = np.random.randint(0,20,30).reshape(5,6)
A

array([[ 6, 17,  2,  1,  6,  8],
       [ 7,  5, 11,  0,  1, 16],
       [ 6, 19,  0,  2, 12,  8],
       [ 8,  6,  3, 19,  8,  4],
       [13, 11, 18, 11, 12, 18]])

### Exercício 3)
Crie uma __view__ da matriz `A` gerada na célula anterior contendo:
- as linhas de `A` com índices 0,1 e 3
- as linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
- as linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3

In [52]:
print('\n matriz original = \n',A)

B = A[[0,1,3]]     # não é view, é fancy index, pode modificar a matriz original em algumas situações
print('\n elementos nas linhas 0,1,3 = \n',B)

B = A[1:3, 0:5:2]   # start, stop, step
#B = A[1:3,[0,2,4]]  # não é view, é fancy index
print('\n elementos nas linhas 1,2 e colunas 0,2,4 = \n',B)

B = A[1:4:2, 1:4:2]      # start, stop, step
#B = A[[1,3]][:,[1,3]]   # não é view, é fancy index
print('\n elementos nas linhas 1,3 e colunas 1,3 = \n',B)


 matriz original = 
 [[ 6 17  2  1  6  8]
 [ 7  5 11  0  1 16]
 [ 6 19  0  2 12  8]
 [ 8  6  3 19  8  4]
 [13 11 18 11 12 18]]

 elementos nas linhas 0,1,3 = 
 [[ 6 17  2  1  6  8]
 [ 7  5 11  0  1 16]
 [ 8  6  3 19  8  4]]

 elementos nas linhas 1,2 e colunas 0,2,4 = 
 [[ 7 11  1]
 [ 6  0 12]]

 elementos nas linhas 1,3 e colunas 1,3 = 
 [[ 5  0]
 [ 6 19]]


### Exercício 4)
Construa um array `A` bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. 
- faça uma cópia do array `A` criado, chamando a cópia de `Ac`
- Substitua todos os elementos do array `A` que sejam maiores que 10 pelo valor -1 
- Substitua todos os elementos do array `Ac` que sejam maiores que 7 e menores que 15 pelo valor -1 

__Dica:__ Gere máscaras booleanas para realizar as modificações nos arrays.

In [31]:
A = np.random.randint(0,20,30).reshape(5,6)
print('\n matriz original = \n',A)

Ac = np.copy(A)
print('\n cópia da matriz original = \n',Ac)

mask = A > 10
A[mask]=-1
print('\nModificando os elementos maiores que 10 na matriz original = \n',A)

mask = (Ac > 7) & (Ac < 15)
Ac[mask]=-1
print('\nModificando os elementos maiores que 7 e menores que 15 na cópia da matriz original = \n',Ac)


 matriz original = 
 [[17 15 11 11 12 10]
 [18  7 12 16 10  7]
 [ 8 14 13  5  1  3]
 [12 19  7  1 15 12]
 [ 1 19  0 19  0 16]]

 cópia da matriz original = 
 [[17 15 11 11 12 10]
 [18  7 12 16 10  7]
 [ 8 14 13  5  1  3]
 [12 19  7  1 15 12]
 [ 1 19  0 19  0 16]]

Modificando os elementos maiores que 10 na matriz original = 
 [[-1 -1 -1 -1 -1 10]
 [-1  7 -1 -1 10  7]
 [ 8 -1 -1  5  1  3]
 [-1 -1  7  1 -1 -1]
 [ 1 -1  0 -1  0 -1]]

Modificando os elementos maiores que 7 e menores que 15 na cópia da matriz original = 
 [[17 15 -1 -1 -1 -1]
 [18  7 -1 16 -1  7]
 [-1 -1 -1  5  1  3]
 [-1 19  7  1 15 -1]
 [ 1 19  0 19  0 16]]


### Exercício 5)
Construa um array `A` com 20 linhas e 10 colunas onde os elementos são os números inteiros de  1 até 200.
- Crie uma __view__ de `A` chamada `A_lpares` contendo apenas as linhas de `A` com índice par. 
- Crie uma __view__ de `A` chamada `A_lpares_cimpares` contendo as linhas `A` com índice par e colunas com índice ímpar. 

In [57]:
A = np.arange(1,201).reshape(20,10)
print('\n matriz original = ', A.shape,'linhas x colunas \n',A)

lpares = A[0::2]
cimpares = A[1::2]

A_lpares = A[0::2]
print('\n linhas de A com índice par = \n',A_lpares)

A_lpares_cimpares = A[0::2, 1::2]
print('\n linhas de A com índice par e colunas com índice ímpar = \n',A_lpares_cimpares)

# Outra resolução:
# lpares = [np.arange(0,A.shape[0],2)]
# cimpares = [np.arange(1,A.shape[1],2)]

# A_lpares = A[lpares]
# print('\n linhas de A com índice par = \n',A_lpares)

# A_lpares_cimpares = A[lpares][:,cimpares]
# # A_lpares_cimpares = A[np.arange(0,A.shape[0],2)][:,np.arange(1,A.shape[1],2)]
# print('\n linhas de A com índice par e colunas com índice ímpar = \n',A_lpares_cimpares)



 matriz original =  (20, 10) linhas x colunas 
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170]
 [171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190]
 [191 192 193 194 195 196 197 198 199 200]]

 linhas de A com índice par = 
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 21  22  23 

### Exercício 6)
Substitua os elememtos do array `A` do exercício anterior por -1 quando pelo menos um dos índices do elemento é par. 

__Dica:__ Construa uma máscara booleana

In [73]:
A = np.arange(1,201).reshape(20,10)
print('\n matriz original = ', A.shape,'linhas x colunas \n',A)

mask = [[(i%2==0) or (j%2==0) for j in range(A.shape[1])] for i in range(A.shape[0])]
mask = np.array(mask).reshape(A.shape[0], A.shape[1])
print('\nmask = \n', mask)
A[mask] = -1
print('\n elementos substituídos nas linhas com índice par e colunas com índice par = \n',A)

# # Outra solução:
# A[0::2] = -1
# A[:,0::2] = -1
# print('\n elementos substituídos nas linhas com índice par e colunas com índice par = \n',A)


 matriz original =  (20, 10) linhas x colunas 
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170]
 [171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190]
 [191 192 193 194 195 196 197 198 199 200]]

mask = 
 [[ True  True  True  True  True  True  True  True  True  True]
 [ True False  Tr

### Exercício 7)
Considere o array `X` de números tipo <font color='blue'>float</font> gerado a partir de uma distribuição uniforme no intervalo entre 0 e 1. Escreva um código para encontrar os três menores valores do array.

__Dica:__ Converta o array em uma lista e ordene.

In [82]:
X = np.random.uniform(low=0.0, high=1.0, size=10)
X = X.tolist() # convertendo a uma lista
print('X:\n', X)
sorted(X)[:3]  # ordenando e selecionando os 3 menores valores


X:
 [0.13412174215814132, 0.6717743083733748, 0.6363154985792794, 0.6350679160274243, 0.10542293421949911, 0.9202085866402063, 0.3582535172640766, 0.898861969161327, 0.28041986074753344, 0.46859361478241535]


[0.10542293421949911, 0.13412174215814132, 0.28041986074753344]

### Exercício 8)
Escreva uma função chamada `troca_colunas` que recebe um array e o índice de duas colunas como parâmetros e retorna o array com as colunas trocadas. Por exemplo:
```python
X = np.array([[0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5]])

X = troca_colunas(X,1,3)
print(X)
```
deve resultar em
```python
[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]
```


In [84]:
def troca_colunas(A,i,j):
   # inclua se codigo aqui
    aux = A[:, i].copy()
    A[:, i] = A[:, j]
    A[:, j] = aux
    return(A)

X = np.array([[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]])
print(X)

X = troca_colunas(X,1,3)
print(X)

[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]
[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]


### Exercício 9)
Os métodos <font color='blue'>vstack</font> e <font color='blue'>hstack</font> do <font color='blue'>numpy</font> empilha matrizes na vertical e horizontal, respectivamente. Por exemplo:
```python
A = [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
B = [[2.0, 2.0, 2.0], [2.0, 2.0, 2.0]]

C = np.vstack((A,B))
print(C)
```
resulta em
```python
[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]
```
Escreva um código para gerar duas matrizes `A` e `B` de números inteiros randômicos no intervalo entre 0 e 10, onde:
- A matriz `A` é 5x6
- A matriz `B` é 5x3

Utilize o método <font color='blue'>hstack</font> para empilhar as matrizes

O que acontece se tentar utilizar o método <font color='blue'>vstack</font>? Explique o motivo da mensagem gerada.

In [88]:
A = np.random.randint(low=0, high=10, size=30).reshape(5,6)
B = np.random.randint(low=0, high=10, size=15).reshape(5,3)

# Empilhando horizontalmente
C = np.hstack((A,B))
print(C)

# Empilhando verticalmente
# Vai dar erro porque para concatenação a dimensão concatenada deve ser exatamente igual nas 2 matrizes
# Porém, nesse caso a quantidade de colunas é diferente em A e em B
# D = np.vstack((A,B))
# print(D)

[[7 9 0 4 3 3 5 9 2]
 [9 4 7 1 8 6 6 0 9]
 [8 6 2 5 6 2 0 3 5]
 [0 5 7 6 0 4 2 9 5]
 [5 1 7 2 8 5 7 2 8]]


### Exercício 10)
Escreva um código para, data uma matriz, zerar todos os elementos abaixo da diagonal principal da matriz. Por exemplo:
```python
[[2 8 3 4 8]
 [4 8 7 7 3]
 [8 2 3 1 4]
 [8 6 3 8 1]
 [6 4 4 6 1]]
```
deve resultar em
```python
[[2 8 3 4 8]
 [0 8 7 7 3]
 [0 0 3 1 4]
 [0 0 0 8 1]
 [0 0 0 0 1]]
```

In [92]:
A = np.random.randint(1,10,25).reshape(5,5)
print('\n matriz original = ', A.shape,'linhas x colunas \n',A)

mask = [[(i>j) for j in range(A.shape[1])] for i in range(A.shape[0])]
mask = np.array(mask).reshape(A.shape[0], A.shape[1])
print('\nmask = \n', mask)
A[mask] = 0
print('\n elementos substituídos abaixo da diagonal principal = \n',A)

# uma alternativa é utilizar o método 'triu' do numpy
A = np.random.randint(1,10,25).reshape(5,5)
A = np.triu(A)
print('\n elementos substituídos abaixo da diagonal principal = \n',A)


 matriz original =  (5, 5) linhas x colunas 
 [[6 3 8 9 4]
 [3 7 1 3 6]
 [6 3 8 2 8]
 [9 9 8 4 1]
 [6 8 7 2 4]]

mask = 
 [[False False False False False]
 [ True False False False False]
 [ True  True False False False]
 [ True  True  True False False]
 [ True  True  True  True False]]

 elementos substituídos abaixo da diagonal principal = 
 [[6 3 8 9 4]
 [0 7 1 3 6]
 [0 0 8 2 8]
 [0 0 0 4 1]
 [0 0 0 0 4]]

 elementos substituídos abaixo da diagonal principal = 
 [[5 7 7 9 8]
 [0 1 3 7 7]
 [0 0 5 7 8]
 [0 0 0 6 4]
 [0 0 0 0 3]]
