# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Programação para Ciência de Dados</span>

## <span style="color:blue">Numpy Parte II e Matplotlib - Avaliação</span>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**
---

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Exercício 1)
Qual dos códigos abaixo corretamente utiliza broadcasting para construir uma matriz cujas **colunas** são todas formadas pelos elementos [0,1,2,3]?
```python
A = np.zeros((4,4))
v = np.arange(4)
```

a)
```python
A[:] = v[:,np.newaxis]
```
b) 
```python
A[:] = v.reshape(4,1)
```
c)
```python
A[:] = v
A = A.T
```
<font color='red'>d) Todas as alternativas estão corretas </font>

In [2]:
A = np.zeros((4,4))
v = np.arange(4)

In [5]:
# A[:] = v[:,np.newaxis]
# A[:] = v.reshape(4,1)
A[:] = v
A = A.T
print(A)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


Resp: Todas estão corretas

### Exercício 2)
Qual das alternativas corretamente explica como o array `W` está sendo calculando no código abaixo?
```python
u = np.random.randint(0,30,7)
v = np.random.randint(0,30,10).reshape(10,1)

W = v + u
```

a) O array `W` possui 10 elementos como resultado da soma dos arrays `u` e `v`, onde `u` é complementado com zeros durante o broadcasting.<br>
<font color='red'>b) O array `W` é uma matriz com 10 linhas e 7 colunas gerado a partir da soma das matriz obtidas do broadcasting do array `v` em 7 colunas e do array `u` em 10 linhas.</font><br>
c) O array `W` é uma matriz com 7 linhas e 10 colunas gerado a partir da soma das matriz obtidas do broadcasting do array `v` em 7 linhas e o array `u` em 10 linhas.<br>
d) O array `W` possui 7 elementos como resultado da soma dos arrays `u` e `v`, onde os três útlimos elementos de `v` são descartados no broadcasting.

In [6]:
u = np.random.randint(0,30,7)
print('Array u:\n',u)
print('Shape do vetor horizontal= ', u.shape, 'Colunas','\n')

v = np.random.randint(0,30,10).reshape(10,1)
print('Array v:\n',v)
print('Shape do vetor vertical= ', v.shape, 'Linhas x Colunas','\n')

W = v + u
print('Matriz W:\n',W)
print('Shape da matriz= ', W.shape, 'Linhas x Colunas','\n')

Array u:
 [ 5 22 17 14  7 10 29]
Shape do vetor horizontal=  (7,) Colunas 

Array v:
 [[13]
 [ 6]
 [21]
 [13]
 [ 6]
 [20]
 [ 0]
 [ 2]
 [15]
 [20]]
Shape do vetor vertical=  (10, 1) Linhas x Colunas 

Matriz W:
 [[18 35 30 27 20 23 42]
 [11 28 23 20 13 16 35]
 [26 43 38 35 28 31 50]
 [18 35 30 27 20 23 42]
 [11 28 23 20 13 16 35]
 [25 42 37 34 27 30 49]
 [ 5 22 17 14  7 10 29]
 [ 7 24 19 16  9 12 31]
 [20 37 32 29 22 25 44]
 [25 42 37 34 27 30 49]]
Shape da matriz=  (10, 7) Linhas x Colunas 



Resp: b

### Exercício 3)
Considere a matriz abaixo. Utilizando redução, encontre o **índice da linha** que possui a maior soma dos elementos.
```python
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])
```
a) linha 6<br>
b) linha 0<br>
<font color='red'>c) linha 8</font><br>
d) linha 9

In [7]:
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])

print('Matriz Inicial A=\n', A)
print('\nSoma de Cada Linha: ',np.sum(A,axis=1))  # soma dos valores em cada linha

soma_linhas = np.sum(A,axis=1)

print('Maior valor dentre todos no vetor: ',np.max(soma_linhas))    # maior valor da matriz/vetor
print('Posição do maior valor dentre todos: ',np.argmax(soma_linhas)) # lineariza a matriz/vetor com A.ravel() e 
                                                                      # retorna a posicão do maior valor

Matriz Inicial A=
 [[5 2 3 6 1 5 7 7 8 9]
 [8 8 3 5 0 1 4 8 3 7]
 [8 0 0 4 2 0 2 6 0 3]
 [5 0 0 4 4 3 5 8 0 0]
 [2 4 2 5 3 4 9 8 0 0]
 [6 7 4 8 5 1 3 5 4 1]
 [6 8 0 5 2 9 3 6 1 6]
 [5 5 2 9 0 5 5 8 2 4]
 [8 8 1 8 4 1 8 9 7 6]
 [5 6 0 9 0 4 9 0 2 0]]

Soma de Cada Linha:  [53 47 25 29 37 44 46 45 60 35]
Maior valor dentre todos no vetor:  60
Posição do maior valor dentre todos:  8


### Exercício 4) 
Considerando a matriz `A` do exercício anterior, qual o **índice da coluna** que possui a menor média de valores?

<font color='red'>a) coluna 2</font><br>
b) coluna 0<br>
c) coluna 8<br>
d) coluna 9

In [8]:
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])

print('Matriz Inicial A=\n', A)
print('\nMédia de Cada Coluna: ',np.mean(A,axis=0))  # soma dos valores em cada coluna

media_colunas = np.mean(A,axis=0)
                      
# B = np.array([np.min(soma_linhas), np.max(soma_linhas), np.min(soma_colunas), np.max(soma_colunas)])
# print('\nResultado Matriz B=\n', B)

print('Menor valor dentre todos no vetor: ',np.min(media_colunas))      # menor valor da matriz/vetor
print('Posição do menor valor dentre todos: ',np.argmin(media_colunas)) # lineariza a matriz/vetor com A.ravel() e 
                                                                        # retorna a posicão do menor valor

Matriz Inicial A=
 [[5 2 3 6 1 5 7 7 8 9]
 [8 8 3 5 0 1 4 8 3 7]
 [8 0 0 4 2 0 2 6 0 3]
 [5 0 0 4 4 3 5 8 0 0]
 [2 4 2 5 3 4 9 8 0 0]
 [6 7 4 8 5 1 3 5 4 1]
 [6 8 0 5 2 9 3 6 1 6]
 [5 5 2 9 0 5 5 8 2 4]
 [8 8 1 8 4 1 8 9 7 6]
 [5 6 0 9 0 4 9 0 2 0]]

Média de Cada Coluna:  [5.8 4.8 1.5 6.3 2.1 3.3 5.5 6.5 2.7 3.6]
Menor valor dentre todos no vetor:  1.5
Posição do menor valor dentre todos:  2


### Exercício 5)
Suponha que a variável `A` no código abaixo é uma matriz com $n$ linhas e $m$ colunas. O que o código está realizando?
```python
Aargs = np.argsort(A)
A[np.arange(A.shape[0]),Aargs[:,-1]] = -1
```
a) Substituindo o maior valor de cada coluna por -1<br>
<font color='red'>b) Substituindo o maior valor de cada linha por -1 </font><br>
c) Substituindo o menor valor de cada linha por -1<br>
d) Substituindo o menor valor de cada coluna por -1

Aargs: O método argsort retorna um array contendo os índices dos elementos ordenados nas linhas.
A.shape[0] = n = número de linhas
Pega todas as linhas da Matriz A indo do range de 0 a n
Pega todas as linhas [:] da matriz de índices das linhas com os elementos ordenados
Pega a coluna [-1] do vetor de índices das linhas com os elementos ordenados, ou seja, o maior valor
E substitui por -1 o maior valor de cada linha
Resp: b

In [15]:
A = np.array([[0, 2, 3], [1, 4, 3], [2, 0, 4], [4, 3, 1]])
print('A= ', A)
Aargs = np.argsort(A)
print('\nAargs= ', Aargs)
# substitui o maior elemento de cada linha por -1
A[np.arange(A.shape[0]),Aargs[:,-1]] = -1
print('\nA= ', A)

A=  [[0 2 3]
 [1 4 3]
 [2 0 4]
 [4 3 1]]

Aargs=  [[0 1 2]
 [0 2 1]
 [1 0 2]
 [2 1 0]]

A=  [[ 0  2 -1]
 [ 1 -1  3]
 [ 2  0 -1]
 [-1  3  1]]
